name: "Blog Title"
description: "Put your description here"
author: ""

# url: "http://localhost:4000"
url: "http://jxnblk.github.io/Heather"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
