name: "Heather"
description: "A Hyperminimal Jekyll Theme"
author: "Jxnblk"

url: "http://jxnblk.github.io/Heather"
baseurl: "/Heather"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /demo/:title
